((NS) => {
    // !!! NEVER COMMIT CREDENTIALS !!!

    NS.HERE_APP_ID = "xWb5KmTI7pgCAFxf9d9P";
    NS.HERE_APP_CODE = "DNMfZLpeUUiLYolfwWKK9A";

    NS.GOOGLE_KEY = "AIzaSyBmg4rmAKFvANZyAKPp8gYvTAgxBKmcrGA";

    NS.MAPBOX_TOKEN = "pk.eyJ1IjoicXRyYW5kZXYiLCJhIjoiSDF2cGNjZyJ9.D1ybOKe77AQDPHkxCCEpJQ";

})(window);
